apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: global-grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana.github.io/helm-charts/
    chart: grafana
    targetRevision: 7.2.5
    helm:
      values: |
        service:
          type: LoadBalancer
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - grafana.hostspacecloud.com
          tls:
          - secretName: grafana-tls
            hosts:
            - grafana.hostspacecloud.com
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
