apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: achebepeterokechukwu
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: achebe
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 15.10.2
    helm:
      values: |
        service:
          type: NodePort
       
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

    
